#!/usr/bin/env python3
from functools import partial
from os import chdir, readlink
from pathlib import Path
from shutil import rmtree
from subprocess import run

myrun = partial(run, check=True)

TEST_DIR_NAME = 'test'

def create_test_dirs():
    remove_test_dir_if_exists()

    print("Creating test dir and test files")
    TEST_DIR.mkdir()
    FROM_DIR.mkdir()
    TO_DIR.mkdir()

    for file in 'one','two','three':
        (TO_DIR / file).touch()


def test_link_directories():
    print("Testing linking two directories")

    cmd = ['./symgr', FROM_DIR, TO_DIR]
    print(f"Running cmd: {cmd}")
    run(cmd)

    print("Test: symlinks are created and point to the right place")
    for file in 'one','two','three':
        # ensure there is a link at FROM_DIR / file pointing to TO_DIR / file
        assert readlink(FROM_DIR / file) == str((TO_DIR / file).resolve())


def test_bless():
    print("Testing blessing a 'dotfile' from source to repo")

    file_to_bless = FROM_DIR / 'dotfile'
    file_to_bless_in_to = (TO_DIR / 'dotfile').resolve()
    contents = 'contents'
    with open(file_to_bless, 'w') as f:
        f.write(contents)

    cmd = ['./symgr', file_to_bless, TO_DIR]
    print(f"Running cmd: {cmd}")
    run(cmd)

    print("Test: symlink is created")
    assert readlink(file_to_bless) == str(file_to_bless_in_to)

    print("Test: file contents match")
    assert open(file_to_bless_in_to).read() == contents

    print("Test: bak file of original is created")
    assert len(list(FROM_DIR.glob('dotfile.bak.20*'))) == 1


def test_symlink():
    print("Testing creating one symlink")

    frm = FROM_DIR / 'symlink'
    to = TO_DIR / 'file'

    frm.touch()
    to.touch()

    cmd = ['./symgr', frm, to]
    print(f"Running cmd: {cmd}")
    run(cmd)

    print("Test: original file is backed up")
    assert len(list(FROM_DIR.glob('symlink.bak.20*'))) == 1

    print("Test: symlink is created and points to the right place")
    assert readlink(frm) == str(to.resolve())


def remove_test_dir_if_exists():
    if TEST_DIR.exists():
        print(f"Test dir {TEST_DIR} exists, removing")
        rmtree(TEST_DIR)


if __name__ == "__main__":
    chdir(Path(__file__).parent)

    TEST_DIR = Path(TEST_DIR_NAME)
    FROM_DIR = TEST_DIR / 'from'
    TO_DIR = TEST_DIR / 'to'

    create_test_dirs()
    test_link_directories()
    test_bless()
    test_symlink()
    remove_test_dir_if_exists()
